# Stop on error
$ErrorActionPreference = "Stop"

Write-Host "Starting build script..."

# Install dependencies 
npm install

# Make sure we have all required dependencies
npm install express-rate-limit node-fetch dotenv cors express

# Copy the correct server.js file
Copy-Item -Path "api-server/server.js" -Destination "server.js"

# Create a simple .env file if it doesn't exist
if (-not (Test-Path -Path ".env")) {
  Write-Host "Creating default .env file..."
  Set-Content -Path ".env" -Value "# Generated by build script"
  Add-Content -Path ".env" -Value "NODE_ENV=production"
  Add-Content -Path ".env" -Value "PORT=3000"
}

Write-Host "Build completed successfully!" 