#!/usr/bin/env bash
# Exit on error
set -o errexit

echo "Starting build script..."

# Install dependencies 
npm install

# Make sure we have all required dependencies
npm install express-rate-limit node-fetch dotenv cors express

# Copy the correct server.js file
cp api-server/server.js server.js

# Create a simple .env file if it doesn't exist
if [ ! -f .env ]; then
  echo "Creating default .env file..."
  echo "# Generated by build script" > .env
  echo "NODE_ENV=production" >> .env
  echo "PORT=3000" >> .env
fi

echo "Build completed successfully!" 